### PR TITLE
Parametrizing EventHandler using monad

### PR DESCRIPTION
**Pull request by katyo**
Allows to use custom monad in `EventHandler` instead of `IO`.
Implementation utilizes `socketAppToIO` method for converting custom monad to `IO`.

```
class SocketAppToIO m m' where
  socketAppToIO :: m (m' a -> IO a)

instance (Monad m) => SocketAppToIO m IO where
  socketAppToIO = return id
```

As you can see, backward compatibility are also present.

So, to use Yesod Handler monad in `EventHandler` we can do it:

```
{-# LANGUAGE FlexibleInstances, MultiParamTypeClasses #-}
instance MonadIO m => SocketAppToIO (HandlerT master m) (HandlerT master IO) where
  socketAppToIO = handlerToIO
```

### CODE REVIEW

**Comment by alexlegg** [comment]
I had a go at doing this inside `ServerAPI`. I added an extra monad to be used for socket handlers and the function `srvSocketAppToIO :: forall a . m1 (m2 a -> IO a)`.

So the Yesod API now has a type like: `ServerAPI (HandlerT s m) (HandlerT s IO)` and defines `srvSocketAppToIO = handlerToIO`.

And because I'm not sure how to do it for Snap either, I just left it as `MonadSnap m => ServerAPI m IO` and `srvSocketAppToIO = return id`.

I also added an example, `chat-store`, that uses Yesod Persist to store chat messages in an Sqlite DB and sends chat history from the login socket handler.

Let me know what you think and if you want me to submit a pull request.

**Comment by ocharles** [comment]
Hi @alexlegg. Sincerest apologies for not replying earlier, but I just wanted to acknowledge your comment. I'm still having a think about this, as it significantly changes the API and is somewhat yesod specific - I think. That said, I definitely get the need for it, so I'm going to try and muse over it a little more and see if I can find any other solutions.

Failing that, your approach is imo the correct one.

**Comment by alexlegg** [comment]
Ok, no worries. I don't have a lot of experience designing haskell APIs, which is why I wanted the feedback. I'm just working off my branch for my project now so I'm not in any huge rush. Let me know what you decide.

**Comment by ocharles** [comment]
You know, now that I think about it more, is there any reason you can't use `handlerToIO` before you call `initialize`?

This would look something like:

```haskell
do runYesod <- runHandlerToIO
     initializer <- initialize yesodAPI (buildRoutingTable state runYesod)

buildRoutingTable state runYesod =
  do on "whatever" (\() -> runYesod someYesodFn)
```

Does that idea seem workable?

**Comment by alexlegg** [comment]
The HandlerT monad doesn't exist at the point where you would normally call `initialize`. `handlerToIO` looks like this: `handlerToIO :: MonadIO m => GHandler sub master (GHandler sub master a -> m a)`.

What would be ideal is if Yesod had a place for doing initialisation inside its own monad but I don't see anything like that in the documentation. I don't like the idea of waiting for a request to come in and then initialising socket.io. 

If all you need is the database, I *think* you could probably just pass the config and connection pool to `buildRoutingTable`. Yesod itself just calls this function on the config/pool it has stored inside `YesodApp`:

`runPool :: ResourceIO m => c -> PersistConfigBackend c m a -> PersistConfigPool c -> m a`

I'd also like to be able to use sessions though and I'm not sure how to do that without a Handler monad.

**Comment by ocharles** [comment]
I am no longer actively using any of these projects, so I will only be providing maintenance for now, and not new features. I think this is slightly too big a change now. If others are still requiring this functionality, please let me know and I can consider re-opening this.

**Pull request closed without merging**
